spring:
  application:
    name: cloud-people
eureka:
  client:
    service-url:
      defaultZone: http://slave2:8081/eureka, http://slave1:8080/eureka
cloud-people:
  ribbon:
     NFLoadBalancerRuleClassName: com.cnpc.Ribbon.MyRule

